services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.144.0
    user: '0:0'
    command:
      - --config=/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13133:13133"
    volumes:
      - ./otel-collector-ci.yaml:/etc/otelcol/config.yaml:ro
      - ./var/otel:/var/otel
