name: example ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 24
  NODE_ENV: pipeline
  JWT_SECRET_PVT: dummydummy
  JWT_SECRET_PUB: dummydummy

jobs:
  e2e:
    name: task example e2e
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install example dependencies
        run: npm install --prefer-offline --no-audit --prefix app

      - name: Build example app
        run: npm run build --prefix app

      - name: Run example e2e tests
        run: npm run test:e2e --prefix app
